### ISSUE TITLE
Logging: Add support for deserializing protobuf payloads.

### ISSUE THREAD

**Issue by salrashid123** [googleapis/python-logging#16]
Cloud logging currently does not parse logging proto message payloads. 

This forces items like GAE RequestLogs to appear serialized under ```payload_pb``` as shown below

```
<google.cloud.logging.entries.ProtobufEntry object at 0x7fa6793621d0>

{
'payload_pb': type_url: "type.googleapis.com/google.appengine.logging.v1.RequestLog"
value: "\n\025s~mineral-minutia-820\022\0011\032T5b26e25700ff0a0425ac3c89260001737e6d696e6572616c2d6d696e757469612d383230000131000100\"\013216.9.110.82\014\010\327\304\233\331\005\020\210\341\200\271\002:\014\010\327\304\233\331\005\020\270\316\373\272\002B\005\020\260\355\372\001R\003GETZ\017/js/myjsfile.jsb\010HTTP/1.1h\260\002p_\202\001hMozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36\242\001\037mineral-minutia-820.appspot.com\320\001\377\377\377\377\377\377\377\377\377\001\330\001\001\262\002\0061.9.54\320\002\001"
, 
'http_request': {'status': 304}, 
'resource': Resource(type=u'gae_app', labels={u'module_id': u'default', u'project_id': u'mineral-minutia-820', u'zone': u'us3', u'version_id': u'1'}), 
'severity': None, 
'insert_id': u'5b26e257000da4438cff347b', 
'timestamp': datetime.datetime(2018, 6, 17, 22, 36, 7, 656421, tzinfo=<UTC>), 
'labels': {u'clone_id': u''}, 
'logger': <google.cloud.logging.logger.Logger object at 0x7fa67b204cd0>, 
'payload': None
}

```
The ```RequestLog``` should get deserialized and placed into the ```payload``` field so its usable

- type.googleapis.com/google.cloud.audit.AuditLog
-  type.googleapis.com/google.appengine.logging.v1.RequestLog
   -   https://github.com/googleapis/googleapis/blob/master/google/appengine/logging/v1/request_log.proto

**Comment by busunkim96** [comment]
FYI The audit log protos are now published https://pypi.org/project/google-cloud-audit-log/

**Comment by daniel-sanche** [comment]
We have now published four proto packages related to logging (thanks Bu Sun):
- https://github.com/googleapis/python-audit-log
- https://github.com/googleapis/python-iam-logging
- https://github.com/googleapis/python-bigquery-logging
- https://github.com/googleapis/python-appengine-logging

I opened a PR to bring in `google.cloud.audit.AuditLog` and `google.appengine.logging.v1.RequestLog` as direct dependencies, since they are listed as officially supported [in the docs](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry). The others won't be imported by default, but the library should be able to recognize them if imported manually.

If anyone thinks any other protos should be added as direct dependencies, feel free to open a bug and we can discuss
