### ISSUE TITLE
Log Router did not publish to the PubSub topic (sink destination)

### ISSUE THREAD

**Issue by aravind08** [googleapis/python-logging#336]
- OS type and version: **N/A**
  - Python version: **N/A**
  - pip version: **N/A**
  - `google-cloud-logging` version: **N/A**

#### Steps to reproduce

**N/A**

I have created a log router which publish to a PubSub topic when my cloud function fails. Last evening, the function failed thrice due to the **_memory limit exceeded_** issue. Logs were created and they fall very well within the **inclusion filter** query. But, it didn't publish to the PubSub topic as intended. 

How do I make this reliable?

A. The Log router config
<img width="654" alt="Screenshot 2021-06-23 at 1 58 19 PM" src="https://user-images.githubusercontent.com/8188445/123065121-80d4a080-d42c-11eb-8bc3-991e6f642476.png">

B. Result of the **Inclusion filter** query:
<img width="1168" alt="Screenshot 2021-06-23 at 1 59 32 PM" src="https://user-images.githubusercontent.com/8188445/123065276-a5307d00-d42c-11eb-9aa2-7d942979a9fd.png">

C. PubSub Trigger in the last 7 days (Incident reported on 2021-06-22 17:01:04.381 IST)
<img width="1166" alt="Screenshot 2021-06-23 at 2 11 39 PM" src="https://user-images.githubusercontent.com/8188445/123065727-0d7f5e80-d42d-11eb-9c63-c538a16f77c2.png">

**Comment by aravind08** [comment]
If this is not the right place to flag this issue, please point me to the appropriate channel. Thanks!

**Comment by daniel-sanche** [comment]
Hey @aravind08, this is a repo for the cloud logging python client library, but it looks like your issue is related to the product backend. [This page](https://cloud.google.com/support/docs/issue-trackers) should give some information about how to submit bug reports to GCP products, and it looks like [this is the link](https://issuetracker.google.com/issues/new?component=187203&template=0) to the public Cloud Logging error report page. That should be the best place to report this

**Comment by aravind08** [comment]
Appreciate this. Thanks!
