### ISSUE TITLE
Add source_location support to AppEngine handler

### ISSUE THREAD

**Issue by remko** [googleapis/python-logging#351]
Several handlers have source_location support. However, it seems to be missing from the AppEngine handler.
Would it be possible to also add source_location support to the AppEngine handler?

**Comment by daniel-sanche** [comment]
Hey remko,

We're planning on deprecating AppEngineHandler in the next v3.0.0 release. GCP has released a lot of new computing environments since this library's first release, and it's not feasible to create custom handlers for each one. Instead, we're switching to two general handlers: `CloudLoggingHandler` for sending logs over the network, and `StructuredLogHandler` for printing JSON logs to standard out (which are then parsed by GCP logging agents). The library will automatically pick the best choice based on the environment.

I'd suggest moving to CloudLogginghandler, which should be essentially the same code as the current AppEngineHandler, plus a few new features like source_location detection.

**Comment by remko** [comment]
@daniel-sanche Thanks for the explanation.

I'm using get_default_handler() (actually even indirectly using setup_logging()).
If I'm getting it correctly, you're saying that this will in a future release use CloudLoggingHandler, but while waiting for this I should manually create my own CloudLoggingHandler.
