### ISSUE TITLE
Support cloud build as a deployment option

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/python-logging#368]

**Comment by tseaver** [comment]
@daniel-sanche Is there already Kokoro configuration in `google3` to support this future build?  I'm asking because all PRs currently have failing builds labeled `Environment - Cloud Build` which fail without any logged output, and I don't see any configuratoin under `.kokoro/environment` to support such a steop.

**Comment by daniel-sanche** [comment]
Yes, I'm in the process of adding cloud build support, along with the necessary kokoro files, in [this PR](https://github.com/googleapis/python-logging/pull/392).

I'm currently blocked waiting on advice from the cloud build team though, because it turns out there are some complications in detecting the build_trigger_id at runtime. I'm hoping to go back and finish the cloud build work by next week

**Comment by meredithslota** [comment]
Closing as we are deprioritizing this as per https://github.com/googleapis/python-logging/pull/392#issuecomment-958054273
