### ISSUE TITLE
docs: add GKE audit Log sample

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/python-logging#427]
show how to build a filter string and retrieve [audit logs](https://googleapis.dev/python/logging/latest/usage.html#retrieving-log-entries)

**Comment by Ecoware** [comment]
Hey guys,
The code in #428 was very helpful to get started.  Thanks !
I've included below what I executed along with the error I'm getting. 
I executed the following code and seemed to have encountered some permissions issues (see all my comments below in **bold** and the error message pasted at the end of this message).
Since I'm developing locally, I authenticate using the Cloud SDK via gcloud auth application-default login.
Thanks for your help !
 

#project_id = os.environ["np-xxx-xxx-xxx-science"]    # **This did not work since I’m working in a local environment so it seemed to be specific to my local Anaconda/Spyder IDE environment**

project_id = "np-xxx-xxx-xxx-science".                          **#  I just hard-coded the project ID string here for insertion into the query string below**

yesterday = datetime.now(timezone.utc) - timedelta(days=1)

time_format = "%Y-%m-%dT%H:%M:%S:%f%z"

filter_str = (

    f'resource.type="k8s_cluster"'

    f'AND logName="projects/{project_id}/logs/cloudaudit.googleapis.com [cloudaudit.googleapis.com]%2Factivity"'

    f'AND timestamp >= "{yesterday.strftime(time_format)}"'

    )

client=google.cloud.logging.Client(project="np-xxx-xxx-xxx-science")   **# The code sample that was provided in the sample did not have this function populated with any parameters so it failed.  I subsequently populated it with the (project  ="np-xxx-xxx-xxx-science") parameter string that you see.  This succeeded and allowed the client object to be set.**

for entry in client.list_entries(filter_=filter_str):          **# Ultimately, the execution of this for loop failed with the error below**

print(entry)

 

**### ERROR:** 

File "/Users/xxxxx/anaconda3/envs/Env2/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking

    raise _InactiveRpcError(state)

 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:

                status = StatusCode.UNAVAILABLE

                details = "Getting metadata from plugin failed with error: ('invalid_grant: reauth related error (invalid_rapt)', '{\n  "error": "invalid_grant",\n  "error_description": "reauth related error (invalid_rapt)",\n  "error_subtype": "invalid_rapt"\n}')"

                debug_error_string = "{"created":"@1635517662.786128000","description":"Getting metadata from plugin failed with error: ('invalid_grant: reauth related error (invalid_rapt)', '{\n  "error": "invalid_grant",\n  "error_description": "reauth related error (invalid_rapt)",\n  "error_subtype": "invalid_rapt"\n}')","file":"src/core/lib/security/credentials/plugin/plugin_credentials.cc","file_line":93,"grpc_status":14}"

>
