### ISSUE TITLE
How to use custom protobuf message with write_log_entries

### ISSUE THREAD

**Issue by iamtodor** [googleapis/python-logging#5]
`google-cloud-logging==1.14.0`
How to use custom protobuf message with `client.write_log_entries`?

My message.proto:
```proto
syntax = "proto3";

message VacancySearchRequest {
    string Query = 1;
    int32 CityId = 2;
    int32 Salary = 3;
    bool NoSalary = 4;
    int32 ScheduleId = 5;
    int32 ProfLevelIds = 6;
    repeated int32 RubricIds = 7;
    int32 ParentId = 8;
    int32 Period = 9;
    bool ShowAgency = 10;
    string Latitude = 11;
    string Longitude = 12;
    int32 Sort = 13;
    repeated int32 VacancyIds = 14;
}
```

Then I compiled it to python.
Then what I do is
```python
    entries = []
    for message in messages:
        parse_dict = ParseDict(message, VacancySearchRequest())
        entry = {
                'json_payload': parse_dict,
            }

            entries.append(entry)

self.client.write_log_entries(entries, log_name='projects/-/logs/-', resource=res)
```
and got the following error:
```
  File "consumer.py", line 159, in <module>
    errors = google_cloud_logging_streamer.send_logs(msg_values_list)
  File "consumer.py", line 94, in send_logs
    resource=res)
  File "env/lib/python3.7/site-packages/google/cloud/logging_v2/gapic/logging_service_v2_client.py", line 474, in write_log_entries
    dry_run=dry_run,
TypeError: Parameter to MergeFrom() must be instance of same class: expected google.protobuf.Struct got VacancySearchRequest.
```

The issue relates to this https://github.com/googleapis/google-cloud-python/issues/7457#issuecomment-555498958, since the documentation doesn't cover any aspect of it: structure/custom protobuf.

**Comment by daniel-sanche** [comment]
Closing this since it's a question, and it's over a year old at this point.

iamtodor: Please re-open if you're still having the issue and I can try to help you debug. I believe the solution is to encode your custom proto as a `google.protobuf.struct_pb2.Struct` using the method described by igorpeshansky (other Struct examples [in the tests](https://github.com/googleapis/python-logging/blob/6a1f19d9929137d4a5ec6bd4d758a16ec5b284e1/tests/unit/test_logger.py#L362)). I can try to throw together some sample code if you're still having issues
