### ISSUE TITLE
Multiple issues while changing the timestamp of a log

### ISSUE THREAD

**Issue by simranchanna** [googleapis/python-logging#542]
I've tried several methods to change the timestamp of a log being sent to cloud logging, but there are a few problems:

1. I'm able to send data only in the past and not in the future while using API directly - (whereas according to the documentation https://cloud.google.com/logging/docs/reference/v2/rest/v2/entries/write the timestamp value can be maximum 24 hours in the future)

2. I'm passing the timestamp value while calling the struct_log method and that timestamp is passed internally in the library functions to where API is called, but that doesn't work at all and as a result, no log is created.

**Comment by daniel-sanche** [comment]
Hey @simranchanna , could you give a code snippet so I can see how you're calling the library, how you're formatting the timestamp, and how you're viewing the logs? I just tried to reproduce this, but it seems to be working for me:

```
import datetime

timestamp = datetime.datetime.now() + datetime.timedelta(minutes=1)
logger.log_struct({"hello":"world", timestamp=timestamp)
```

I noticed the log doesn't appear in the Log Explorer until the time denoted in the timestamp, so that may be why it appears that no log is created. But let me know if you're seeing something different

**Comment by lmesz** [comment]
Hey @daniel-sanche,

I tried a little modified version of your code:
```import datetime
from google.cloud import logging
log_name="onetwo"

client = logging.Client()
logger = client.logger(log_name)
timestamp = datetime.datetime.now() - datetime.timedelta(minutes=1)
print(timestamp)
logger.log_struct({"hello":"world", "message": "appletree"}, timestamp=timestamp)
```

I tried to see the sent logs in Logs Explorer and in the given log but didn't see any. I am in CET timezone and the Logs Explorer is set to this timezone as well.
Can you give me some hint either how to debug further or what I am doing wrong?
Thank you

**Comment by daniel-sanche** [comment]
Nothing you're doing stands out as wrong to me. To help debug: can you show me what filters you're using in log explorer and what GCP environment you're running the code on? Do you see any logs if you omit the `timestamp` changes?

**Comment by lmesz** [comment]
Yeah I saw logs when I omitted the timestamp field.
Figured out the problem was how the datetime was set to timestamp field. 
I needed to change
from `timestamp = datetime.datetime.now() - datetime.timedelta(minutes=1)`
to `timestamp = (datetime.datetime.now() - datetime.timedelta(minutes=1)).astimezone()`

**Comment by daniel-sanche** [comment]
Ok great, glad you got it working
