### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by bearprevent** [googleapis/python-logging#623]
#### Environment details

  - OS type and version: Ubuntu 22.04.1
  - Python version: `3.10.4`
  - pip version: `22.0.2`
  - `google-cloud-logging` version: `3.2.2`

#### Steps to reproduce

Loading the logging library already uses more than 40MB.
This is quite a burden for smaller systems.

Is there any alternative way of using this library without such a memory footprint?

  1. `python -c 'import os; print(os.system(f"ps -q {os.getpid()} -o rss="))`
    - `7888 KB`
  2. `python -c 'import os; import google.cloud.logging; print(os.system(f"ps -q {os.getpid()} -o rss="))'`
    - `50424 KB`

**Comment by daniel-sanche** [comment]
We don't currently have a smaller-footprint version of the library, but I'll try to investigate ways to slim it down

**Comment by pnico** [comment]
We have an appengine app running entirely on F1 instances (384 MB limit). We often get "Exceeded memory limit" warnings and/or instances are killed if one of our endpoints uses too much memory, so avoiding/mitigating this is a routine part of development for us. Can I assume this library isn't officially recommended for our use case?

**Comment by daniel-sanche** [comment]
Hey pnico,

I also [responded this in a different thread](https://github.com/googleapis/python-logging/issues/149#issuecomment-1538692607) but in case it's helpful here as well: App Engine and serverless GCP environments can use the [StructuredLogHandler](https://github.com/googleapis/python-logging/blob/c1c8ce158f566150319c2d4fb2f068b10668d507/google/cloud/logging_v2/handlers/structured_log.py#L60) provided by this library to take advantage of the environment's built-in stdout capture. Importing and this Handler alone should significantly cut down on memory usage, since you can avoid the overhead needed for making network calls.

Or alternatively, you can use the StructuredLogHandler as a template and make an even more slimmed-down version, if you're only interested in certain logging fields.

Let me know if code samples related to this would be helpful
