### ISSUE TITLE
Library Fetching Node Metadata 

### ISSUE THREAD

**Issue by Shalevro2** [googleapis/python-logging#833]
#### Environment details

  - OS type and version: ubuntu 22.04
  - Python version: Python 3.10.12
  - pip version: pip 23.3.1
  - `google-cloud-logging` version: 3.2.1 (also at 3.9.0)

#### Steps to reproduce

  1. Run the following code example on a pod.

#### Code example

```python

from google.cloud.logging_v2.client import Client
from google.oauth2 import service_account


def auth():
    credentials_path = "<PATH>"

    application_sa = service_account.Credentials.from_service_account_file(credentials_path)
    logging_client = Client(credentials=application_sa)

    log_name = "Test log"

    return logging_client.logger(log_name)


def write(level, message, labels=None):
    logger = auth()
    logger.log_text(str(message), labels=labels, severity=level)


if __name__ == "__main__":
    write("WARNING", "This is a test")
```

When running the code above we see that the package is making an http request to 169.254.169.254 port 80.
This behavior is not what we expected because we pass the credentials in the client constructor.
Is there way to make it not doing this request?

**Comment by gkevinzheng** [comment]
@Shalevro2 Is this pod deployed on GKE or is this a more custom setup?

**Comment by Shalevro2** [comment]
@gkevinzheng Deployed on GKE

**Comment by gkevinzheng** [comment]
@Shalevro2 Even if you do pass credentials in to the logging library, the resource detector still queries the metadata server to determine the environment in which you are running in. This is done when you create a logger from your client:
https://github.com/googleapis/python-logging/blob/37aab7f15b63e51d458080b3425529f52fdff7a6/google/cloud/logging_v2/client.py#L209

This code will instantiate a `Logger` object, and since you didn't pass in a resource, it will automatically infer it via `detect_resource`: 
https://github.com/googleapis/python-logging/blob/37aab7f15b63e51d458080b3425529f52fdff7a6/google/cloud/logging_v2/logger.py#L76-L78

which uses metadata server calls as part of its detection procedure. To prevent it from doing this, you can pass in your own `logging_v2.resource.Resource` type similar to this: https://github.com/googleapis/python-logging/blob/37aab7f15b63e51d458080b3425529f52fdff7a6/google/cloud/logging_v2/handlers/_monitored_resources.py#L101-L109

Personally I wouldn't recommend doing this to cut down on a metadata server call, but it is possible.

**Comment by Shalevro2** [comment]
@gkevinzheng It's works, appreciate it. Thanks!
